### ISSUE TITLE
怎么获得预训练模型？

### ISSUE THREAD

**Issue by chenrxi** [VISION-SJTU/USOT#10]
你好，请问预训练模型是在什么数据上训练得到的吗？有预训练的超参吗？

**Comment by zhengjilai** [comment]
Q: how the pretrained model is obtained ?

A: For the supervised backbone (imagenet_pretrain), it is directly collected from [TracKit](https://github.com/researchmm/TracKit) as Ocean is our base tracker.  For the self-supervised backbone (moco v2), it is directly collected from the [MoCo](https://github.com/facebookresearch/moco) project.

**Comment by chenrxi** [comment]
thank you for your answer
