### ISSUE TITLE
About the memory

### ISSUE THREAD

**Issue by LiShenglana** [VISION-SJTU/USOT#16]
Hi, I wonder that what's the difference of accurary and success rate between the model trained with and without memory?  I am looking forward to getting your reply. Thank you very much!

**Comment by zhengjilai** [comment]
Thank you for your interest. 

Looking back on USOT today (it has been 2 years), I'd like to say that cycle memory actually combined two useful components in one novelty. The first is long-term temporal exploration, and the second is memory-based learning. In my experience, the former is extremely useful for all datasets, and the improvement is qualitative. While the latter is very useful for VOT benchmarks, but only gives marginal improvement on other benchmarks (see ULAST, CVPR2022). If you have conducted lots of ablation study, you may have already noticed the phenomenon mentioned above. 

I am not sure if what I say solves your problem. Feel free to contact me if your question has not been solved.

**Comment by LiShenglana** [comment]
> Thank you for your interest.
> 
> Looking back on USOT today (it has been 2 years), I'd like to say that cycle memory actually combined two useful components in one novelty. The first is long-term temporal exploration, and the second is memory-based learning. In my experience, the former is extremely useful for all datasets, and the improvement is qualitative. While the latter is very useful for VOT benchmarks, but only gives marginal improvement on other benchmarks (see ULAST, CVPR2022). If you have conducted lots of ablation study, you may have already noticed the phenomenon mentioned above.
> 
> I am not sure if what I say solves your problem. Feel free to contact me if your question has not been solved.

My problem solved! Thanks very much for your reply! The cycle memory mechanism is also useful in some RGB-T datasets. The effect of the module does vary with the datasets.
