### ISSUE TITLE
When the pre-training model "imagenet_pretrain.model" is not loaded, the training results are very poor

### ISSUE THREAD

**Issue by Scott233** [VISION-SJTU/USOT#17]
Is it necessary to load pre-trained backbone？
And is there any way to make the network independent of the parameters of the pre-training model？
Thank you very much！

**Comment by zhengjilai** [comment]
That is a very good question. 

When I was studying unsupervised tracking 2 years ago, I actually built three variants of USOT. The first loaded imagenet supervised pretraining backbone (USOT* in paper), the second loaded unsupervised backbone Moco v2 (USOT in paper), and the last randomly initialized the backbone (just as UDT, CVPR2019). I noticed that the former two gave similar results, but the results of the third variant was very poor. 

From USOT and ULAST (CVPR2022), it seems that pretrained backbone is currently still important for unsupervised tracking. It may be an interesting problem whether the pretrained backbone weights can be dropped.

**Comment by Scott233** [comment]
> That is a very good question.
> 
> When I was studying unsupervised tracking 2 years ago, I actually built three variants of USOT. The first loaded imagenet supervised pretraining backbone (USOT* in paper), the second loaded unsupervised backbone Moco v2 (USOT in paper), and the last randomly initialized the backbone (just as UDT, CVPR2019). I noticed that the former two gave similar results, but the results of the third variant was very poor.
> 
> From USOT and ULAST (CVPR2022), it seems that pretrained backbone is currently still important for unsupervised tracking. It may be an interesting problem whether the pretrained backbone weights can be dropped.

Thank you very much for your answers and directions！
