### ISSUE TITLE
bbox_picked_freq = track_info['meta']['bbox_picked_freq']

### ISSUE THREAD

**Issue by zrz1018** [VISION-SJTU/USOT#3]
When running the train model, key error meta appears.

**Comment by zhengjilai** [comment]
The key 'meta' should be constructed successfully after running the [gen_json.py](https://github.com/VISION-SJTU/USOT/blob/main/preprocessing/datasets_train/vid/gen_json.py) script in preprocessing. 

You may need to: 1. Check whether your train.json files for every dataset are generated correctly (at least equipped with the key 'meta'). 2. Set breaking points in dataloader to see what you really have read in the loader. 

I have noticed your email and I will explain that in email as soon as possible. Thanks for your trust.

**Comment by Mao-216** [comment]
I have faced the same problem. How did you solve it?

**Comment by Mao-216** [comment]
I faced the same question.How did you solve it?

**Comment by zrz1018** [comment]
时间已经过去一年了，具体解决细节我忘记了。我的建议：这个报错是由于数据集出现问题了，而不是源码的问题，而且很可能只是其中一个数据集出现了问题，大概率是LaSOT。你可以尝试直接使用作者提供的百度网盘中的数据集来进行训练，保证下载解压过程正确。你也可以采用作者源码中的裁剪数据集，生成flow.json文件的方式获取训练数据。
